### PR TITLE
feat: add `blas/base/srotm`

### PR DESCRIPTION
**Pull request by aman-095**
## Description

> What is the purpose of this pull request?

This RFC proposes to add a routine to apply a modified Givens plane rotation on single-precision floating-point vectors as defined in [BLAS Level 1](http://www.netlib.org/blas/#_level_1) routines. Specifically adding `@stdlib/blas/base/srotm` is proposed.

## Related Issues

> Does this pull request have any related issues?

None.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @aman-095.

Please note that you can help make PR review go faster by ensuring that you're adhering to project style conventions. The Fortran implementation did not conform to how we write Fortran elsewhere, which meant I needed to go through and make various style changes. Minimizing that work will help make review more straightforward.

**Comment by kgryte** [comment]
Also, please make sure that declarations match CBLAS (see https://github.com/OpenMathLib/OpenBLAS/blob/1ba1b9c357fb7d5916a56a6c388b4aea47aad395/lapack-netlib/CBLAS/include/cblas.h#L131). In this case, all the signatures needed to be updated from `param[5]` to `param`. Given that we need to interface with system libraries (i.e., code we don't control), we have to conform to CBLAS conventions; we cannot deviate in function signatures. Otherwise, we run the risk of breaking code, as users will have divergent expectations.

**Comment by kgryte** [comment]
@aman-095 Sorry. I just realized that this PR did not perform float32 emulation in the JS implementations. Can you submit a follow-up PR ensuring float32 arithmetic in JS? Thanks.

**Comment by aman-095** [comment]
Sure, @kgryte, I will do that.

**Pull request merged**
