### PR TITLE
Replace internal constants with package constants

### LINKED ISSUE #74: Update base math implementations to use package constants
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue.

Some of the base implementations in the `stdlib` math use constants internally which are available as packages; e.g., `@stdlib/math/constants/float64-half-pi`, etc.

To ensure consistency across the codebase, would be of benefit to replace internal constants with package constants, where available.

For constants not having package constants, these values can stay as is.

## Related Issues

> Does this issue have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/master/FAQ.md

### PR DESCRIPTION
**Pull request by chrisdamba**
Resolves #74.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

* [x] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
* [x] Read and understand the [Code of Conduct][code-of-conduct].
* [x] Read and understood the [licensing terms][license].
* [x] Searched for existing issues and pull requests __before__ submitting this pull request.
* [x] Filed an issue (or an issue already existed) __prior to__ submitting this pull request.
* [x] Rebased onto latest `develop`.
* [x] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

* updates base math implementations for pi/2 and pi/4 to use package constants

## Related Issues

> Does this pull request have any related issues?

This pull request:

* resolves #74

## Questions

> Any questions for reviewers of this pull request?

Yes. I've noticed variable naming in the examples (e.g for pi/4 variables are declared as `FOUTRH_PI`) is different from the names in the function implementation (e.g `PIO4`), is this ok?

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

---

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/master/CONTRIBUTING.md
[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[license]: https://github.com/stdlib-js/stdlib/blob/master/LICENSE

### CODE REVIEW

**Comment by kgryte** [comment]
@chrisdamba Yes, aliasing the constants with different names is fine. Packages are allowed some flexibility in how they alias dependencies.

**Review by kgryte — APPROVED** [review]

**Comment by kgryte** [comment]
@chrisdamba PR looks good. Need to wait on @Planeshifter to submit a patch for broken tests. Once he does, if you could rebase on the latest so we can at least check that canary builds pass on Circle CI before merging, that would be awesome. Will ping once ready to rebase.

Oh, and one minor nit: I would not classify the changes as a "hotfix", as code is not currently broken. Instead, I would classify the changes as a "feature" (i.e., general improvement, not a patch). No need to change your branch name; just for future reference.

**Comment by chrisdamba** [comment]
Thanks @kgryte for the review, much appreciated!

**Comment by kgryte** [comment]
@chrisdamba Patch pushed. Should be good to rebase and force push to update this PR.

**Review by kgryte — APPROVED** [review]

**Pull request merged**
