### PR TITLE
Add support for computing tribonacci numbers

### LINKED ISSUE #322: RFC: add support for computing tribonacci numbers
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for computing [tribonacci numbers](https://en.wikipedia.org/wiki/Generalizations_of_Fibonacci_numbers#Tribonacci_numbers). This would be similar to the package `@stdlib/math/base/special/fibonacci` for computing fibonacci numbers.

The implementation would have the following package name:

Package: `@stdlib/math/base/special/tribonacci`
Alias: `base.tribonacci`

Additional resources:

-   [OEIS](https://oeis.org/A000073)
-   [list of tribonacci numbers](https://oeis.org/A000073/b000073.txt)

## Related Issues

> Does this feature request have any related issues?

None.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ShraddheyaS**
Resolves #322 .

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
-   [X] Read and understand the [Code of Conduct][code-of-conduct].
-   [X] Read and understood the [licensing terms][license].
-   [X] Searched for existing issues and pull requests **before** submitting this pull request.
-   [X] Filed an issue (or an issue already existed) **prior to** submitting this pull request.
-   [X] Rebased onto latest `develop`.
-   [X] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

-   Adds support for computing tribonacci numbers

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #322 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

Yes, `using Printf` was ot working for me for some reason, changed it to Compat.Printf as per [this thread](https://discourse.julialang.org/t/using-printf/12919/5).

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[license]: https://github.com/stdlib-js/stdlib/blob/develop/LICENSE

### CODE REVIEW

**Comment by kgryte** [comment]
@ShraddheyaS What version of Julia are you using?

**Comment by kgryte** [comment]
@Planeshifter We have yet to update the `REQUIRE` files, correct? Looks like we still have Julia `0.5` in the `REQUIRE` file, hence the issue with `Printf`.

**Review by kgryte — APPROVED** [review]
@ShraddheyaS LGTM! I'll make some minor changes on my end, but this looks good to go! Thanks for working on this!

**Comment by Planeshifter** [comment]
> @Planeshifter We have yet to update the `REQUIRE` files, correct? Looks like we still have Julia `0.5` in the `REQUIRE` file, hence the issue with `Printf`.

Yes, that is correct. Will do shortly.

**Comment by kgryte** [comment]
@Planeshifter Great! Thanks!

**Pull request merged**
