### PR TITLE
feat: add `blas/base/isamax`

### PR DESCRIPTION
**Pull request by aman-095**
## Description

This RFC proposes to add a routine to find the index of the first element having maximum absolute value as defined in [BLAS Level 1](http://www.netlib.org/blas/#_level_1) routines. Specifically adding `@stdlib/blas/base/isamax` is proposed.

## Related Issues

> Does this pull request have any related issues?

None.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by Pranavchiku** [comment]
This will be simple to review, I'll review this and `idamax` today evening ( IST )

**Comment by Pranavchiku** [comment]
Can you please iterate over changes made in `idamax` and see if this PR has anything to change?

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @aman-095.

Note that I had to make a number of small changes. So would be worthwhile on your side to do a file-by-file review to minimize typos, etc, in future PRs, especially when porting changes from one PR to another, as in the BLAS work.

**Comment by aman-095** [comment]
Sure, @kgryte will review all the files once before pushing. Thanks for reviewing and merging this PR.

**Pull request merged**
