### PR TITLE
feat: add `constants/float64/num-high-word-significand-bits`

### PR DESCRIPTION
**Pull request by gunjjoshi**
## Description

> What is the purpose of this pull request?

This pull request:

-   adds `constants/float64/num-high-word-significand-bits`, which would help to complete the TODO at: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/pow/src/main.c#L52.

```js
FLOAT64_NUM_HIGH_WORD_SIGNIFICAND_BITS = 20;
```

## Related Issues

> Does this pull request have any related issues?

None.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
In terms of naming conventions, we have a couple of (semi-)relevant precedents:

- `@stdlib/constants/float64/precision`: no indication that it refers to the number of bits.
- `@stdlib/constants/float64/num-bytes`: uses the `num-` prefix to indicate that it refers to a quantity.

When I first saw `high-word-significand-bits`, I initially thought it was a high word mask. Only upon reading the code did I recognize that this referred to the number of bits in the significand.

My personal preference would be to rename the package and constant name to make its intent more obvious. Potential names:

- `@stdlib/constants/float64/num-high-word-significand-bits`
- `@stdlib/constants/float64/high-word-precision`

I think my preference is the first option, but I am open to suggestions.

**Comment by gunjjoshi** [comment]
@kgryte Thanks for explaining. That definitely makes sense. 

`num-high-word-significand-bits` seems good, but could be quite long for a normal user. But, if that is not a major problem, I'll update this everywhere in this PR.

**Comment by kgryte** [comment]
This pkg will be used rarely enough that length is not a huge concern. You may need to disable the ESLint rule for id-length each time the constant variable is declared in JS.

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @gunjjoshi!

**Pull request merged**
