### PR TITLE
docs: fix REPL examples in `stats/ttest`

### PR DESCRIPTION
**Pull request by Snehil-Shah**
## Description

> What is the purpose of this pull request?

This pull request:

-   fixes incorrect REPL example code

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   was discovered in #2273

## Questions

> Any questions for reviewers of this pull request?

While trying to commit, I encountered a bunch of REPL lint errors.

```json
{
  "file": "/workspaces/stdlib/lib/node_modules/@stdlib/stats/ttest/docs/repl.txt",
  "errors": [
    {
      "id": "@stdlib/_tools/repl-txt/rules/doctest",
      "severity": "error",
      "message": "Malformed return annotation. Encountered error while parsing: Bad object",
      "start": 81,
      "end": 184
    },
    {
      "id": "@stdlib/_tools/repl-txt/rules/doctest",
      "severity": "error",
      "message": "Malformed return annotation. Encountered error while parsing: Bad object",
      "start": 81,
      "end": 184
    },
    {
      "id": "@stdlib/_tools/repl-txt/rules/doctest",
      "severity": "error",
      "message": "`Paired t-test` should be wrapped in single quotes",
      "start": 81,
      "end": 184
    },
    {
      "id": "@stdlib/_tools/repl-txt/rules/doctest",
      "severity": "error",
      "message": "`One-sample t-test` should be wrapped in single quotes",
      "start": 81,
      "end": 184
    },
    {
      "id": "@stdlib/_tools/repl-txt/rules/doctest",
      "severity": "error",
      "message": "Malformed return annotation. Encountered error while parsing: Bad object",
      "start": 81,
      "end": 184
    },
    {
      "id": "@stdlib/_tools/repl-txt/rules/doctest",
      "severity": "error",
      "message": "`One-sample t-test` should be wrapped in single quotes",
      "start": 81,
      "end": 184
    },
    {
      "id": "@stdlib/_tools/repl-txt/rules/doctest",
      "severity": "error",
      "message": "`One-sample t-test` should be wrapped in single quotes",
      "start": 81,
      "end": 184
    },
    {
      "id": "@stdlib/_tools/repl-txt/rules/code-semicolons",
      "severity": "error",
      "message": "Semicolons must not be omitted if output is suppressed",
      "start": 81,
      "end": 184
    },
    {
      "id": "@stdlib/_tools/repl-txt/rules/code-semicolons",
      "severity": "error",
      "message": "Semicolons must not be omitted if output is suppressed",
      "start": 81,
      "end": 184
    }
  ]
}
```
I am to be blamed for the error due to `code-semicolons` rule originating in #2435. The updated rule doesn't work for multi-line inputs, as it's checking line by line. For instance, the line `for ( i = 0; i < 20; i++ ) {` doesn't have both the output and semicolon.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Review by kgryte — APPROVED** [review]
LGTM.

**Comment by kgryte** [comment]
@Snehil-Shah Can you wrap the output of `out.print()` in single quotes? Hopefully that will resolve some of the lint errors.

**Comment by kgryte** [comment]
The use of `print()` should have been changed a while ago, but I don't believe @Planeshifter has gotten around to refactoring the various stats testing packages.

**Comment by Snehil-Shah** [comment]
I tried; apparently, it's a problem with multi-line outputs.

```json
{
  "message": "Displayed return value is `Paired t-test`, but expected `Paired t-test\n\nAlternative hypothesis: True difference in means is not equal to 0\n\n pValue: 0.9339\n statistic: 0.0832\n df: 99\n 95% confidence interval: [-0.5539,0.6024]\n\nTest Decision: Fail to reject null in favor of alternative at 5% significance level\n` instead"
}
```

**Review by Planeshifter — APPROVED** [review]
Let's land this; `doctest` linting has a few edge cases we need to fix but that shouldn't hold up this change.

**Pull request merged**
