### PR TITLE
feat: add C implementation for `math/base/special/coversin`

### PR DESCRIPTION
**Pull request by Userf1995**
Resolves a part of #649 .

## Description

> What is the purpose of this pull request?

This pull request:

-   add C implementation for math/base/special/coversin

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves a part of #649.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

### CODE REVIEW

**Review by Pranavchiku — COMMENTED** [review]
We cannot do this, as it depends on `math/base/special/sin` which do not have `C` implementation. This PR will be blocked.

**Comment by Rejoan-Sardar** [comment]
### lkkl;l,m

**Comment by Userf1995** [comment]
**lkjhgfvcdfvgbhjkl;lkjhbv******

**Comment by Rejoan-Sardar** [comment]
### kjhghujlk
kj**hjklkjnj**klkm;klkmn
kjnjmklkm

**Pull request closed without merging**
