### PR TITLE
Add C implementation for `@stdlib/math/base/special/cosh`

### LINKED ISSUE #748: [RFC]: Add C implementation for `@stdlib/math/base/special/cosh`
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/cosh`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/cosh).

```c
double stdlib_base_cosh( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by Pranavchiku**
Resolves #748.

## Checklist

- [x] update readme.md
- [x] include.gypi
- [x] binding.gyp
- [x] include/stdlib/math/base/special/
- [x] src
- [x] manifest.json
- [x] lib
- [x] examples
- [x] benchmark
- [x] test
* * *

@kgryte

### CODE REVIEW

**Comment by Pranavchiku** [comment]
All tests passed and benchmarks cleared, this PR can have a final review.

**Comment by kgryte** [comment]
@Pranavchiku This appears to be a duplicate of https://github.com/stdlib-js/stdlib/pull/732.

**Comment by kgryte** [comment]
Should #732 or this PR be preferred?

**Comment by Pranavchiku** [comment]
This is redundant, I might have missed it when I cleaned up my PC for a fresh installation of Ubuntu 22.04.
PR: #732 , can be preferred over this.

**Comment by kgryte** [comment]
Okay. Will close.

**Pull request closed without merging**
