### PR TITLE
docs: improve examples of `stats/base/dists/kumaraswamy`

### LINKED ISSUE #1632: [RFC]: improve README examples of `stats/base/dists/kumaraswamy` namespace
### Description

This RFC proposes to improve the [README examples](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base/dists/kumaraswamy#examples) of the `stats/base/dists/kumaraswamy` namespace package. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality.

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the [contents](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base/dists/kumaraswamy) of the `stats/base/dists/kumaraswamy` namespace and identify interesting functions and packages to showcase.
- Update the example code block in the "Examples" section of the README for the `stats/base/dists/kumaraswamy` namespace and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by ruthwikchikoti**
Resolves #1632 

## Description

> What is the purpose of this pull request?

This pull request:

-   a 
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1632 
-   fixes #1632 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by ruthwikchikoti** [comment]
hey @kgryte can you please review this !!!!!!!!!!!!

**Comment by ruthwikchikoti** [comment]
I wanted to check if there are any issues affecting the merge of my pull request. If so, please let me know, and I'll be happy to make any necessary updates. @kgryte

**Comment by ruthwikchikoti** [comment]
@kgryte  waiting for your reply !!!

**Comment by ruthwikchikoti** [comment]
@kgryte  can you please review !!!

**Comment by ruthwikchikoti** [comment]
@kgryte waiting !!

**Comment by ruthwikchikoti** [comment]
hey @Planeshifter can you please review this !! its being a long time waiting for your reply !

**Review by Planeshifter — APPROVED** [review]
Made some small edits and will merge shortly.

Just for future reference, one of the reasons I didn't review this PR earlier was that the new examples contained a call to a `random` function that doesn't exist in our `stats/base/dists` namespaces, which you would have noticed if even running the example code a single time.  

Reviewing PRs takes work, and you can expect quicker feedback when showing that you did the necessary work to ensure your PR is of high-quality.

But either way, thanks for your contribution, which I will merge shortly.

**Pull request merged**
