### PR TITLE
feat: add `blas/base/ssymv`

### PR DESCRIPTION
**Pull request by aman-095**
## Description

> What is the purpose of this pull request?

This RFC proposes to add a routine to perform one of the matrix-vector operations `y = alpha*A*x + beta*y` where alpha and beta are scalars, x and y are n element vectors and A is an n by n symmetric matrix as defined in [BLAS Level 2](http://www.netlib.org/blas/#_level_2) routines. Specifically adding `@stdlib/blas/base/ssymv` is proposed.

## Related Issues

> Does this pull request have any related issues?

None.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
@aman-095 I've done a partial review and refactor: benchmarks, docs, examples, and `ssymv.js`. You should pay particular attention to `ssymv.js`. I've leave it to you to apply to `ndarray.js` and to update the rest of the documentation and tests.

**Comment by aman-095** [comment]
Sure, Athan will review those and apply changes elsewhere.

**Comment by kgryte** [comment]
@aman-095 One thing which is missing from the tests are column-major variants. All test fixtures atm are row-major.

**Comment by kgryte** [comment]
@aman-095 We also need to add assertion tests in order to get 100% code coverage.

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @aman-095.

For the other related PRs, you'll want to compute the diff between your last commit and the current state. That will help inform you as to what changes need to be propagated to `ssbmv` and others.

Note that I went ahead and added tests for edge cases, assertions, and column-major. Those will also need to be added to other PRs.

**Pull request merged**
