### PR TITLE
feat: add C implementation for `math/base/special/factorial`

### PR DESCRIPTION
**Pull request by gunjjoshi**
## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for [`math/base/special/factorial`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/factorial).

```c
double stdlib_base_factorial( const double x );
``` 

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves a part of #649.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
@gunjjoshi We should amend the signature to be

```c
double stdlib_base_factorial( const int32_t x );
```

Having double precision input in C doesn't make sense for this package.

**Comment by gunjjoshi** [comment]
> @gunjjoshi We should amend the signature to be
> 
> ```c
> double stdlib_base_factorial( const int32_t x );
> ```
> 
> Having double precision input in C doesn't make sense for this package.

Sure, I'll update this.

**Comment by gunjjoshi** [comment]
> @gunjjoshi We should amend the signature to be
> 
> ```c
> double stdlib_base_factorial( const int32_t x );
> ```
> 
> Having double precision input in C doesn't make sense for this package.

@kgryte Wouldn't this lead to different behaviors in `C` and `JavaScript`? For instance, currently:

```js
var v = factorial( 0.5 );
// returns ~0.886
```  

But, in `C`, this won't be possible, as we will have only integers as input.

**Comment by kgryte** [comment]
Ah wait. You're right. I forgot about the gamma approximation. Disregard my comment

**Review by Planeshifter — APPROVED** [review]
Looks all well; will merge shortly.

**Pull request merged**
