### PR TITLE
Added '@stdlib/math/base/special/cot'

### LINKED ISSUE #227: RFC: add support for computing the cotangent (cot)
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for computing the cotangent. The initial implementation is straightforward:

```javascript
return 1.0 / tan( x );
```

Package: `@stdlib/math/base/special/cot`
Alias: `base.cot`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

Reference implementations:

-   [Julia](https://github.com/JuliaLang/julia/blob/dee7d77c199c4776cf4e06afb7ce920f09ad3c8c/base/special/trig.jl#L958)

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by dorrin-sot**
Resolves #227 .

## Description

> What is the purpose of this pull request?

This pull request:
- Is a feature which adds the module `cot(x)` to stdlib

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #227

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
@dorrin-sot Thanks for this PR. For your class assignment, is the goal to simply make a contribution (e.g., file a PR) or to engage in a peer-review process?

If the latter, I can provide detailed feedback; otherwise, I can be sparing in any changes that would need to be made on your end.

**Comment by dorrin-sot** [comment]
Making a PR is enough for it though I can fix/improve anything I did wrong

**Review by kgryte — APPROVED** [review]
This PR needs fairly extensive clean-up and refactoring; however, I'll do that on our end. Thanks for your contribution, @dorrin-sot!

**Comment by kgryte** [comment]
Refactored and clean-up in https://github.com/stdlib-js/stdlib/commit/0d1a31646773799e808d0159f1db08183fb68fb9.

**Pull request merged**
