### PR TITLE
feat: add @stdlib/math/iter/sequences/tribonacci

### LINKED ISSUE #1331: [RFC]: add `@stdlib/math/iter/sequences/tribonacci`
### Description

This RFC proposes adding the package `@stdlib/math/iter/sequences/tribonacci`.

The package should be similar in structure as [`@stdlib/math/iter/sequences/fibonacci`](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/math/iter/sequences/fibonacci).

Package: `@stdlib/math/iter/sequences/tribonacci`
Alias: `iterTribonacciSeq`

### Related Issues

None.

### Questions

No.

### Other

[Tribonacci sequence](https://en.wikipedia.org/wiki/Generalizations_of_Fibonacci_numbers#Tribonacci_numbers)

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by PraneGIT**
Resolves #1331 

## Description

> What is the purpose of this pull request?

adding the package @stdlib/math/iter/sequences/tribonacci.

The package is similar in structure as [@stdlib/math/iter/sequences/fibonacci](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/math/iter/sequences/fibonacci).

Package: @stdlib/math/iter/sequences/tribonacci
Alias: iterTribonacciSeq

This pull request:

-   adds the package @stdlib/math/iter/sequences/tribonacci.

## Related Issues

> Does this pull request have any related issues?
No.
This pull request:

-   resolves #1331 
-   fixes #1331 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by Jaysukh-409** [comment]
@PraneGIT You should update the Copyright year from 2019 to 2024.

**Review by Planeshifter — APPROVED** [review]
This looks great, thank you @PraneGIT! Should be ready to land after CI has passed.

**Pull request merged**
