### PR TITLE
Add arccosecant hyperbolic implementation

### LINKED ISSUE #235: RFC: add support for computing the inverse hyperbolic cosecant (acsch)
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for computing the inverse hyperbolic cosecant. The initial implementation is straightforward:

```javascript
return asinh( 1.0 / x );
```

Package: `@stdlib/math/base/special/acsch`
Alias: `base.acsch`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

Reference implementations:

-   [Julia](https://github.com/JuliaLang/julia/blob/dee7d77c199c4776cf4e06afb7ce920f09ad3c8c/base/special/trig.jl#L983)

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by AlisaLC**
Resolves #235 

## Description

> What is the purpose of this pull request?

This pull request:

-   in the issue it stated that `acsch(h)` is supposed to be implemented using `asinh(x)` but since it was not already in the repo i implemented it using `ln(x)` and `sqrt(x)` with some small accuaracy improvement.
- tests are included as well for negative and positive values

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
@AlisaLC Thanks for this contribution!

Quick question: how did you determine that your implementation provides an accuracy improvement? What is this compared to?

**Comment by kgryte** [comment]
Also, is there a reference implementation on which you based on your current implementation?

**Comment by AlisaLC** [comment]
I just implemented it using the original formula and improved the accuracy by using `log1p` and `sqrt1pm1` when `x` is large enough instead of `ln` and `sqrt` so it has a small accuracy improvement.

**Review by kgryte — APPROVED** [review]
This PR needs refactoring and clean-up and still contains vestiges of having copied code and docs from `acosh`; however, I'll handle the clean-up on our end. Thanks for the contribution @AlisaLC.

**Comment by kgryte** [comment]
Refactored and cleaned up in https://github.com/stdlib-js/stdlib/commit/8de89716f928a64dece49a88f6ffb6a2566fde32.

**Pull request merged**
