### PR TITLE
feat: adds C implementation for math/base/special/fast/max

### PR DESCRIPTION
**Pull request by Userf1995**
Resolves a part of  #649  .

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C implementation for math/base/special/fast/max

## Related Issues

> Does this pull request have any related issues?

This pull request:

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by Pranavchiku** [comment]
Hey @Rejoan-Sardar if you are facing some problem at #1900, #1902, I'll recommend you to fix those first than opening new PRs.

**Comment by Rejoan-Sardar** [comment]
> Hey @Rejoan-Sardar if you are facing some problem at #1900, #1902, I'll recommend you to fix those first than opening new PRs.

Yes @Pranavchiku I am working on it.

**Comment by Pranavchiku** [comment]
These dummy PRs are blocking others to work on these issues. Please work on one PR at a time. Select one of those and close others.

**Comment by Rejoan-Sardar** [comment]
> These dummy PRs are blocking others to work on these issues. Please work on one PR at a time. Select one of those and close others.

@Pranavchiku don't close please wait some time,I was done commit without git add

**Comment by Rejoan-Sardar** [comment]
[int](ia;flfesd;cml;av)

**Comment by Rejoan-Sardar** [comment]
Email: [rejoansardar4@gmail.com](mailto:rejoansardar4@gmail.com)   Phone: +91-7319341385

**Comment by Rejoan-Sardar** [comment]
Email: [rejoansardar4@gmail.com](mailto:rejoansardar4@gmail.com), [rejoan@lpu.nic.in](mailto:rejoan@lpu.nic.in)   Phone: +91-7319341385

**Pull request closed without merging**
