### PR TITLE
feat: add `array/base/braodcasted-ternary3d`

### LINKED ISSUE #3164: [RFC]: add `array/base/broadcasted-ternary3d`
### Description

This RFC proposes adding a new package to the `array/base/*` namespace: `@stdlib/array/base/broadcasted-ternary3d`.

This package is the ternary equivalent of [`@stdlib/array/base/broadcasted-binary3d`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/array/base/broadcasted-binary3d).

To provide a concrete example of what a PR adding the desired package should contain, see [`@stdlib/array/base/broadcasted-ternary2d`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/array/base/broadcasted-ternary2d), which is the 2D package equivalent.

While the package proposed in this RFC will **not** match the implementations found in the above packages, those packages should provide a conceptual idea of what is desired. Do **not** simply copy-paste the code found in those packages.

### Notes

- If you are interested in contributing a PR which addresses this RFC and are a **first-time contributor** or not yet familiar with our project conventions, please do **not** submit LLM-generated code. Please consult our [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md) and the associated [development guide](https://github.com/stdlib-js/stdlib/blob/develop/docs/development.md). Failure to respect project conventions will result in your PR being rejected without review. Thank you for understanding!

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `[RFC]:`.

### PR DESCRIPTION
**Pull request by Vinit-Pandit**
Resolves #3164 

## Description

> What is the purpose of this pull request?

This pull request:

-   adding implementation of `array/base/braodcasted-ternary3d`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3164 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

-   [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)
* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by Neerajpathak07** [comment]
Pls use a backtick while naming packages.
Ex:- `array/base/broadcasted-ternary3d`

**Comment by Vinit-Pandit** [comment]
> Pls use a backtick while naming packages. Ex:- `array/base/broadcasted-ternary3d`

Can u please point me out @Neerajpathak07 ?

**Comment by Neerajpathak07** [comment]
Sure whenever you are naming files or packages in the PR title or description write it in this way:-
image

**Comment by kgryte** [comment]
@MeastroZI This PR has varying space conventions. Please update to ensure that there are spaces **inside** brackets and parens (e.g., `( t )` and `[ 1, 2, 3 ]` and `[ i4 ]`). The dominant convention in this project is to include spaces, and we expect all PRs to follow those conventions. This likely also applies to your other open PRs.

**Comment by Vinit-Pandit** [comment]
@stdlib-js/reviewers

**Review by kgryte — APPROVED** [review]
LGTM. Thanks for working on this, @MeastroZI. 

For reference, I made various clean-up changes in https://github.com/stdlib-js/stdlib/pull/3228/commits/438efb93b8cb72f86d48af4a87021c53f6bd4606. I recommend checking that commit to determine if similar changes should be applied to your other open PRs.

**Comment by Vinit-Pandit** [comment]
This small things are really hard to catch, for me atleast 🥲🤧 ,  
Thank you @kgryte  i will take a close look on this commit !

> LGTM. Thanks for working on this, @MeastroZI.
> 
> For reference, I made various clean-up changes in ### ### [438efb9](https://github.com/stdlib-js/stdlib/commit/438efb93b8cb72f86d48af4a87021c53f6bd4606). I recommend checking that commit to determine if similar changes should be applied to your other open PRs.

**Pull request merged**
