### PR TITLE
Add C implementation for `@stdlib/math/base/special/erf`

### LINKED ISSUE #647: [RFC]: Add C implementation for `@stdlib/math/base/special/erf`
### Description

This RFC proposes adding a C implementation for [`@stdlib/math/base/special/erf`](https://github.com/stdlib-js/stdlib/blob/b43a75923e47775446d3b6d7219ee42e07f7ce63/lib/node_modules/%40stdlib/math/base/special/erf).

```c
double stdlib_base_erf( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by Pranavchiku**
Resolves #647.

## Checklist

- [x] update readme.md
- [x] include.gypi
- [x] binding.gyp
- [x] include/stdlib/math/base/special/
- [ ] evalpoly.js
- [ ] src
- [ ] manifest.json
- [ ] lib
- [ ] examples
- [ ] benchmark
- [ ] test
* * *

@kgryte

### CODE REVIEW

**Comment by Pranavchiku** [comment]
It requires C-Implementation of `exp`.

**Comment by kgryte** [comment]
@Pranavchiku You can keep this one open and just work on `exp`. Once `exp` is merged in, you can pick back up on this PR.

**Comment by Pranavchiku** [comment]
Trouble makes the unrelated history (while merging upstream/develop), so as it didn't have much progress, I will just copy its changes to another PR, once `exp` gets merged.

**Comment by kgryte** [comment]
At some point, I'd recommend doing the following:

1. Delete your local copy of `stdlib` and the fork on your GitHub.
2. Create a clean fork of the GitHub repository.
3. Clone your fork to your local machine.
4. Configure `upstream` to be the `stdlib-js/stdlib.git` repo and `origin` to be your fork.
5. From then on, always sync your local `develop` with the upstream `develop` by running `git pull upstream develop`.
6. Create a branch from your `develop`: `git checkout -b feat/foo`.
7. When needing to sync your branch, run `git pull upstream develop`.

**Comment by Pranavchiku** [comment]
Yeah sure !

**Pull request closed without merging**
