### PR TITLE
Add support for computing the inverse/arc cotangent (acot)

### LINKED ISSUE #233: RFC: add support for computing the inverse/arc cotangent (acot)
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for computing the inverse (arc) cotangent. The initial implementation is straightforward:

```javascript
return atan( 1.0 / x );
```

Package: `@stdlib/math/base/special/acot`
Alias: `base.acot`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

Reference implementations:

-   [Julia](https://github.com/JuliaLang/julia/blob/dee7d77c199c4776cf4e06afb7ce920f09ad3c8c/base/special/trig.jl#L983)

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by JithinKS97**
Resolves #233 .

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
-   [x] Read and understand the [Code of Conduct][code-of-conduct].
-   [x] Read and understood the [licensing terms][license].
-   [x] Searched for existing issues and pull requests **before** submitting this pull request.
-   [x] Filed an issue (or an issue already existed) **prior to** submitting this pull request.
-   [x] Rebased onto latest `develop`.
-   [x] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

-   Add support for computing the inverse/arc cotangent (acot)

## Related Issues

> Does this pull request have any related issues?

- This pull request:

-   resolves #233 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

The test fixtures for the arccot function were generated using Julia ```1.4.2``` where as in the other parts of the code base, an older version of ```0.5``` is used and the function ```range``` is used instead of ```linspace``` as ```linspace``` is deprecated in the newer version of julia.

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[license]: https://github.com/stdlib-js/stdlib/blob/develop/LICENSE

### CODE REVIEW

**Comment by kgryte** [comment]
@JithinKS97 Awesome! Will review shortly!

**Comment by kgryte** [comment]
@JithinKS97 Looks good! The only questions I have are:

1.  The Julia `REQUIRE` file for generating test fixtures still says `0.5`. Can you update this? And what version of `JSON` was necessary to support the Julia version?
2.  Did you have to refactor the Julia benchmarks file? If so, would you be able to update the `REQUIRE` file there? This will probably entail updating the `BenchmarkTools` dependency.

Thanks!

**Comment by JithinKS97** [comment]
@kgryte I've updated the ```REQUIRE``` in test It is now
```
julia 1.4.2
JSON 0.21.0
```
In the benchmark, I had to change the ```@printf``` function to ```print``` to make it run with Julia 1.4.2. The ```REQUIRE``` file in bench mark now is 
```
julia 1.4.2
BenchmarkTools 0.5.0

```
Also when I ran c benchmark file, I got the warning
```
benchmark.c: In function ‘main’:
benchmark.c:124:9: warning: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
  srand( time( NULL ) );
```
Which got removed when I included time.h in header. Can I keep it that way?

**Comment by kgryte** [comment]
@JithinKS97 Re: `time.h`. I am surprised this bug has taken so long to discover. We've been missing that header in all the C benchmark files. My guess is that the C compilers we've used up until this point have automatically included it, similar to `math.h`.

In short, yes, keep the `time.h` include.

**Comment by kgryte** [comment]
@JithinKS97 Thanks for updating the REQUIRE files! LGTM.

**Review by kgryte — APPROVED** [review]
@JithinKS97 Looks good to me. Merging! Thanks for working on this!

**Comment by JithinKS97** [comment]
Thanks very much

**Comment by kgryte** [comment]
@JithinKS97 For reference, I did a final tidy in this commit https://github.com/stdlib-js/stdlib/commit/a9a6661638d27664b7b2157ccbe6e92387889887 to match project conventions (style, etc), fix some "bugs" on our end (erroneous info in the `package.json`), and test/benchmark behavior (testing `+-inf`, adjusting value ranges to ensure better "branch coverage" in the underlying implementation, etc). May be useful to review when working on the other functions.

**Comment by JithinKS97** [comment]
@kgryte Noted that :+1:

**Pull request merged**
