### PR TITLE
test: add tests to `@stdlib/ndarray/base/nullary`

### LINKED ISSUE #2229: [RFC]: add tests for `@stdlib/ndarray/base/nullary`
### Description

Currently, the `@stdlib/ndarray/base/nullary/test/test.js` only tests whether the main export is a function.

This RFC proposes to add tests to verify:

- The first argument provided is an ndarray-like object

- The input ndarray-like object contains valid `data`, `dtype`, `shape`, `stride`, `offset`, and `order` properties

- No modification occurs if the `data` property of the input ndarray-like object is empty

- The second argument provided is a function

- The second argument returns a value compatible with the `dtype` of the output ndarray

- The `nullary` function returns void

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by headlessNode**
Toward #2229 

## Description

> What is the purpose of this pull request?

This pull request:

-   adds tests for `@stdlib/ndarray/base/nullary`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   adds tests toward resolving #2229 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

I added some edge cases for  `blockednullary2d` up to `blockednullary4d` (same for related complex data types) to get 100% coverage. But I don't know if I used the most feasible methods. I'd like some insight into that, thanks.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by headlessNode** [comment]
@Planeshifter @kgryte Please review, thanks.

**Comment by headlessNode** [comment]
@kgryte @Planeshifter Ping, reminder.

**Review by kgryte — CHANGES_REQUESTED** [review]
@headlessNode Thanks for working on this. I made some changes. The main thing is splitting out the tests for the various dimensions into separate files for future maintenance. We do this for other packages, especially those which require extensive test suites, and so it makes sense to follow suit here.

I've only refactored up to 2D. For 3D and up, the files should be similar to `test.2d.js`. One important change is that the unit tests test against the public interface, rather than the individual implementation files. By testing against the interface, we ensure that end-to-end tests work as expected and intended code paths are exercised.

To generate coverage reports, from the root project directory,

```bash
$ make test-cov TESTS_FILTER=".*/ndarray/base/nullary/.*"
$ make view-cov
```

To ensure relevant code paths were exercised, I also included additional tests for 2D, such as contiguity, non-contiguity, singleton dimensions, etc. I'd expect something similar to 3D+.

If you wouldn't mind continuing the test refactoring, then we can move full steam ahead and get these tests in! Thanks for your patience!

**Comment by headlessNode** [comment]
@kgryte Sure. Thanks for the guidance.

**Comment by headlessNode** [comment]
@kgryte Hi, as I'm working through the refactoring, the expected array of dimension 7D+ is getting really large, 100s of elements. Here's the example shape, and stride for 7D 	
```
sh = [ 2, 2, 2, 2, 2, 2, 2 ];
st = [ 128, 64, 32, 16, 8, 2, 1 ];
```
Is this Okay or should I try to reduce it somehow?

**Comment by kgryte** [comment]
You can use leading singleton dimensions. E.g., `shape = [ 1, 1, 1, 1, 2, 2, 2 ] `. To get full code coverage, you may need to use permutations (e.g., `shape = [ 2, 1, 2, 1, 1, 1, 2 ]`, etc).

**Comment by headlessNode** [comment]
Alright, thanks.

**Comment by headlessNode** [comment]
@kgryte Please review, thanks.

**Review by kgryte — APPROVED** [review]
LGTM. The primary missing tests needed at this point to achieve full test coverage are for blocked iteration. I've added tests for 2D blocked iteration. In order to avoid bogging this PR down further, I suggest we go ahead and merge. Any further tests can be added in follow-up PRs.

Thanks, @headlessNode, for working on this.

**Pull request merged**
