### PR TITLE
feat: add a stdlib ASCII art in REPL's default welcome message

### LINKED ISSUE #2175: [RFC]: add stdlib ASCII art in REPL's default welcome message
### Description

This RFC proposes adding a stdlib ASCII art in the default welcome message in the REPL.

I think it looks cool:

stdlibjs

stdlib

*The above ASCII art was generated using [this](https://patorjk.com/software/taag/#p=display&f=Standard&t=stdlib-js) website*

### Related Issues

None

### Questions

No.

### Other

Inspired by the Julia REPL and many other CLI applications.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by Snehil-Shah**
Resolves #2175

## Description

> What is the purpose of this pull request?

This pull request adds a stdlib ASCII art in the default welcome message of the REPL.

Some design combinations I tried are attached below:

- ### Julia type partitioning

  - **Current implementation**:
julia_std
  
  - We can add/remove more spaces to make it more spread-out/compact:
julia_std_nospace
julia_std_spacetop

  - A Tall typeface:
julia_tall

- ### Simple design

  simple_nospace

- ### A dramatic design I made myself (personally, not a fan)

  dramatic_1
  dramatic_2

@kgryte all yours to choose... I prefer the current implementation or a more compact version of it

There are various other fonts available [here](https://patorjk.com/software/taag/#p=display&f=BlurVision%20ASCII&t=stdlib) too, although most are a bit too dramatic for a REPL application IMO...
If we are looking for even smaller arts, [*rectangles*](https://patorjk.com/software/taag/#p=display&f=Rectangles&t=stdlib), [*small*](https://patorjk.com/software/taag/#p=display&f=Small&t=stdlib) etc are some of the good fonts 

We can also explore incorporating some colors into our welcome message, now or in the future...

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #2175

## Questions

> Any questions for reviewers of this pull request?

Can we shorten the text `'For more info about stdlib, see the source repository:'` to just `'For more info, see the source repository:'` or `'see the source repository:'`? It better aligns with the rest of the block giving us a fixed width as attached below:

image

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
@Snehil-Shah The first design is good. And yes to abbreviating the "For more info,".

**Comment by kgryte** [comment]
I think you either want the vertical dashed line to either align with the API descriptions OR the tag text to align with the API descriptions.

**Comment by kgryte** [comment]
In the last screenshot in "Questions", you don't have either, so can appear misaligned.

**Comment by Snehil-Shah** [comment]
@kgryte Personally, they don't appear misaligned to me, as the API docs and the art above are two different entities which themselves look pretty symmetrical on their own.

image

Here are the designs after trying to align them. Looks good too:

image

With equal spacing around the vertical line. Honestly looks cluttered:

image

Aligning the vertical line looks worse imo:

image

What do you prefer?

**Comment by kgryte** [comment]
Let's go with the first. That is what is currently implemented in this PR, correct?

**Comment by Snehil-Shah** [comment]
@kgryte This is currently implemented:

image

If by first, you meant this, then this PR is good to go👍

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @Snehil-Shah!

**Pull request merged**
