### PR TITLE
fix: add missing ndarray test fixture

### PR DESCRIPTION
**Pull request by rotu**
## Description

> What is the purpose of this pull request?

This pull request:

-   fixes broken tests in ndarray https://github.com/stdlib-js/ndarray/actions/workflows/test.yml?query=branch:main

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [X] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by rotu** [comment]
Backstory: I was looking at using stdlib ndarray but saw the "test: failing" CI badge at https://github.com/stdlib-js/ndarray, which gave me pause. I'm not sure if this is *all* that's needed to fix the tests.

Also, I copied the code from https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/ndarray/dispatch/test/fixtures/fill.js. It seems to me like maybe `fill` is a useful operation in itself, not just for test code. But I'm not yet familiar enough with the code.

**Comment by kgryte** [comment]
> Backstory: I was looking at using stdlib ndarray but saw the "test: failing" CI badge at [stdlib-js/ndarray](https://github.com/stdlib-js/ndarray), which gave me pause. I'm not sure if this is all that's needed to fix the tests.

Ah! Unless you need the entire namespace, I suggest using the individual packages. E.g.,

```bash
$ npm install @stdlib/ndarray-array
```

The omission of the fixture file is my fault. I believe I have it on another dev machine. Let me circle back.

> It seems to me like maybe fill is a useful operation in itself, not just for test code. 

Indeed. The main thing holding this up is implementing the C kernel, which we haven't had the bandwidth to address. For the test fixtures, it's fine if these implementations are not optimal, as we don't care as much about raw perf, but they aren't really appropriate as general packages.

We do have lower-level implementations which do implement kernels (e.g., `@stdlib/ndarray/base/unary`, where, when the callback is a "constant" function, can be used to fill an output array), but these implementations are arguably a bit heavyweight and not as ergonomic when used in tests.

**Review by kgryte — APPROVED** [review]
I, indeed, had failed to commit this file. The implementation matches the uncommitted file. Will merge in order to resolve failing builds.

**Comment by kgryte** [comment]
Thanks, @rotu!

**Pull request merged**
