### PR TITLE
test: add tests to `blas/ext/base/dnannsumkbn`

### LINKED ISSUE #3201: [RFC]: Incomplete code coverage for `blas/ext/base/dnannsumkbn`
### Description

This RFC proposes to add a test case in each of the relevant test files. The test case should handle the situation where the stride is `0` and the first element is `NaN`.

Coverage report: https://coverage.stdlib.io/blas/ext/base/dnannsumkbn/index.html
For reference see: https://github.com/stdlib-js/stdlib/pull/3051

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Other

No.

### Checklist

- [x] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.
- [x] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by saurabhraghuvanshii**
Resolves #3201.

## Description

> What is the purpose of this pull request?

This pull request:

-   Adds test case for blas/ext/base/dnannsumkbn

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #3201 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by headlessNode** [comment]
@saurabhraghuvanshii The test failure is from a downstream test suite. Not from this PR.

**Comment by saurabhraghuvanshii** [comment]
@headlessNode so I have to nothing with it

**Comment by headlessNode** [comment]
@saurabhraghuvanshii Yes. The PR is looking good.

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @saurabhraghuvanshii!

**Comment by kgryte** [comment]
As the CI failure is due to an expected downstream test failure and will be fixed in a subsequent PR/commit, I'll go ahead and merge.

**Pull request merged**
