### PR TITLE
feat: add `blas/base/dznrm2`

### PR DESCRIPTION
**Pull request by aman-095**
## Description

> What is the purpose of this pull request?

This RFC proposes to add a routine to find the euclidean norm of a complex double-precision floating-point vector as defined in [BLAS Level 1](http://www.netlib.org/blas/#_level_1) routines. Specifically adding `@stdlib/blas/base/dznrm2` is proposed.

## Related Issues

> Does this pull request have any related issues?

None.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Review by kgryte — CHANGES_REQUESTED** [review]
Marking this PR as needing changes for similar reasons as #2270 .

**Comment by kgryte** [comment]
@aman-095 LMK when this PR is ready for review.

**Comment by aman-095** [comment]
Hey, @kgryte, I have added `C` and `Fortran` implementation to this.

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @aman-095.

**Pull request merged**
