### PR TITLE
Add support for reviving a JSON serialized regular expression

### PR DESCRIPTION
**Pull request by steff456**
Resolves https://github.com/stdlib-js/todo/issues/412.

## Description

> What is the purpose of this pull request?

This pull request:

-   adds support for deserializing a JSON to RegExp

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves https://github.com/stdlib-js/todo/issues/412

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

Please note that this PR is dependent on with https://github.com/stdlib-js/stdlib/pull/521, once that one is merged I will update this branch and add the examples and benchmark that depend on that package.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
@steff456 Now that #521 has been merged, this PR should be unblocked.

**Comment by steff456** [comment]
I'll rebase this one then 😉

**Comment by kgryte** [comment]
Instead of rebasing, you can also just `merge` the `develop` branch into this branch.

**Review by kgryte — APPROVED** [review]
Thanks, @steff456!

**Pull request merged**
