### PR TITLE
feat: add `ndarray/base/map`

### PR DESCRIPTION
**Pull request by headlessNode**
Progresses #2656.

## Description

> What is the purpose of this pull request?

This pull request:

-   Adds a `base` implementation of `Array.prototype.map` method for `ndarrays`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   Progresses #2656. 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

This is a work-in-progress pull request.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by headlessNode** [comment]
@kgryte As discussed, I've implemented the kernels up to 3d and the related files. Please review.

**Comment by kgryte** [comment]
@headlessNode Thanks for working on this. What you have thus far looks great! Just made some minor edits to ensure the descriptions/conventions match other similar packages. Should be good to continue building this out. 🚀

**Comment by headlessNode** [comment]
@kgryte All kernels implemented. Please review, thanks!

**Comment by kgryte** [comment]
@headlessNode Am I right in thinking that you'd like a review before we add tests?

**Comment by headlessNode** [comment]
@kgryte Yes. But if you'd prefer, I can implement the tests before your review.

**Comment by kgryte** [comment]
I think you are right to wait, lest we need to make any changes.

**Review by kgryte — APPROVED** [review]
LGTM. @headlessNode I think we can go ahead and merge this and then add tests in a follow-up PR. That work for you?

**Comment by kgryte** [comment]
Re: the failing benchmarks CI job. I can confirm that the benchmarks run as expected. I ran them locally and all succeeded. Given the number of benchmarks, we're simply at the mercy of GitHub CI time limits.

**Comment by headlessNode** [comment]
@kgryte I have started to work on the tests. I'll open a PR when completed.

> I can confirm that the benchmarks run as expected.

Yes, I also checked multiple times on my end ran as expected.

**Comment by kgryte** [comment]
Great! I'll go ahead and merge! 🚀

**Comment by headlessNode** [comment]
Lots of learning with this one. Thanks for your help @kgryte

**Comment by kgryte** [comment]
Awesome! I know it's a slog, so thanks for persisting!

**Pull request merged**
