### PR TITLE
feat: add `blas/base/matrix-triangle-str2enum` & `blas/base/matrix-triangle/enum2str`

### PR DESCRIPTION
**Pull request by Pranavchiku**
## Description

> What is the purpose of this pull request?

This pull request adds implementation for `blas/base/matrix-triangle-str2enum` & `blas/base/matrix-triangle/enum2str`

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by Pranavchiku** [comment]
Repl Lint Failure happens in `matrix-triangle-enum2str`:

This happens even if I copy and use https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/blas/base/transpose-operation-enum2str/docs/repl.txt exact same with no modifications.

```console
% git commit -m "chore: add docs/repl.txt"
/Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/_tools/repl-txt/rules/doctest/lib/main.js:175
			alias = alias.split( '.' );
			              ^

TypeError: Cannot read properties of null (reading 'split')
    at replaceAliases (/Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/_tools/repl-txt/rules/doctest/lib/main.js:175:18)
    at String.replace (<anonymous>)
    at replace (/Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/string/base/replace/lib/main.js:49:13)
    at replace (/Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/string/replace/lib/main.js:78:9)
    at Object.returnValues [as validate] (/Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/_tools/repl-txt/rules/doctest/lib/main.js:131:12)
    at Linter.validate (/Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/_tools/repl-txt/validate/lib/validate.js:110:32)
    at isValid (/Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/_tools/repl-txt/validate/lib/main.js:42:9)
    at onRead (/Users/pranavchiku/repos/stdlib-js/stdlib/lib/node_modules/@stdlib/_tools/lint/repl-txt/lib/lint.js:93:11)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)

Node.js v20.9.0

REPL help lint errors.
```

**Review by Pranavchiku — COMMENTED** [review]
This is done by copy pasting files from  corresponding `transpose-operation-*` using `cp -r transpose-operation-enum2str/* matrix-triangle-enum2str/` and then find and replace. I am not sure why we have lint error in `repl.txt` for `enum2str`.

**Comment by Pranavchiku** [comment]
The trouble is in line `> var out = {{alias}}( {{alias:@stdlib/blas/base/matrix-triangle-str2enum}}( 'upper' ) )`, with the following diff it works:

```diff
--- a/lib/node_modules/@stdlib/blas/base/matrix-triangle-enum2str/docs/repl.txt
+++ b/lib/node_modules/@stdlib/blas/base/matrix-triangle-enum2str/docs/repl.txt
@@ -15,7 +15,7 @@
 
     Examples
     --------
-    > var out = {{alias}}( {{alias:@stdlib/blas/base/matrix-triangle-str2enum}}( 'upper' ) )
+    > var out = {{alias}}( 121 )
     'upper'
 
     See Also
```

**Comment by kgryte** [comment]
@Pranavchiku This lint error is expected. The package is not yet in the REPL namespace. We can ignore for now.

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @Pranavchiku!

**Pull request merged**
