### PR TITLE
feat: add C ndarray interface and refactor implementation for `stats/base/dnanmin`

### PR DESCRIPTION
**Pull request by aayush0325**
Resolves None

## Description

> What is the purpose of this pull request?

This pull request:

-   adds C ndarray intreface for `stats/base/dnamin`
-   refactors JavaScript implementation
-   refactors tests, docs, benchmarks and examples.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves None

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by aayush0325** [comment]
Same question here as #4206, What to use for generating random arrays with `NaN` values, left the JS examples and benchmarks untouched for now

**Review by Planeshifter — APPROVED** [review]

**Comment by Planeshifter** [comment]
@aayush0325 

We have done things like this:

```js
var discreteUniform = require( '@stdlib/random/base/discrete-uniform' );
var bernoulli = require( '@stdlib/random/base/bernoulli' );
var filledarrayBy = require( '@stdlib/array/filled-by' );

function rand() {
        if ( bernoulli( 0.2 ) ) {
                return NaN;
        }
        return discreteUniform( 0, 100 );
}

var x = filledarrayBy( 10, 'float64', rand );
```

**Comment by aayush0325** [comment]
> @aayush0325
> 
> We have done things like this:
> 
> ```js
> var discreteUniform = require( '@stdlib/random/base/discrete-uniform' );
> var bernoulli = require( '@stdlib/random/base/bernoulli' );
> var filledarrayBy = require( '@stdlib/array/filled-by' );
> 
> function rand() {
>         if ( bernoulli( 0.2 ) ) {
>                 return NaN;
>         }
>         return discreteUniform( 0, 100 );
> }
> 
> var x = filledarrayBy( 10, 'float64', rand );
> ```

I'll push the required changes here and everywhere else, Thanks @Planeshifter!

**Comment by aayush0325** [comment]
I've pushed a fix, let me know if there's anything to be changed here @Planeshifter. I'll make similar changes in all my other PRs after i get the green light here

**Comment by Planeshifter** [comment]
@aayush0325 To preserve the existing behavior and range of generated values, might be better to use the uniform instead of discrete uniform, as it looks like we didn't just benchmark for integer values here. I only meant the code snippet as an example of how we have done it elsewhere, namely in some of the extended BLAS base packages, not that we should change to discrete uniform or draw from a different range than was previously done.

Otherwise looks good to me.

**Comment by aayush0325** [comment]
ah, my bad i'll revert the commit just a sec

**Comment by aayush0325** [comment]
please give this a final look @Planeshifter! sorry for the misunderstanding.

**Comment by Planeshifter** [comment]
@aayush0325 Just pushed a commit with what I envisioned: Basically updating the benchmarks to avoid the for-loops while not changing the distribution from which the values are drawn. Does that make sense?

Thanks for the PR and your proactive approach in updating open ones, which makes life as a reviewer much easier! 

I can merge this PR shortly after CI once all checks are green.

**Review by Planeshifter — APPROVED** [review]

**Comment by aayush0325** [comment]
> Basically updating the benchmarks to avoid the for-loops while not changing the distribution from which the values are drawn. Does that make sense?

got it, updating all other similar PRs like this soon, thanks for all your help!

**Pull request merged**
