### PR TITLE
Add csch

### LINKED ISSUE #229: RFC: add support for computing the hyperbolic cosecant (csch)
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for computing the hyperbolic cosecant. The initial implementation is straightforward:

```javascript
return 1.0 / sinh( x );
```

Package: `@stdlib/math/base/special/csch`
Alias: `base.csch`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

Reference implementations:

-   [Julia](https://github.com/JuliaLang/julia/blob/dee7d77c199c4776cf4e06afb7ce920f09ad3c8c/base/special/trig.jl#L958)

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by dorrin-sot**
Resolves #229.

## Description

> What is the purpose of this pull request?

This pull request:

-   Implement `csch(x)` using `sinh(x)`

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #229
-   fixes #229

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by dorrin-sot** [comment]
@kgryte Hi again! Sorry, I'm done with two PRs but when I try to push my commits to my fork I get the following log from git. It was working fine like 3 hours ago but ever since I was suddenly unable to push to the branches in my fork :(

```
Running C benchmark files...
Running benchmark: /Users/dorrinsotoudeh/Downloads/stdlib/lib/node_modules/@stdlib/math/base/special/asec/benchmark/c/benchmark.c
Resolving package path...
Package path: /Users/dorrinsotoudeh/Downloads/stdlib/lib/node_modules/@stdlib/math/base/special/asec
Resolving package manifest...
Unable to resolve package manifest.
Compiling benchmark...
Successfully compiled benchmark.
Success!
TAP version 13
# c::asec
should not return NaN
should not return NaN
  ---
  iterations: 1000000
  elapsed: 0.000000954
  rate: 1048576000000.000000000
  ...
ok 1 benchmark finished
# c::asec
should not return NaN
should not return NaN
  ---
  iterations: 1000000
  elapsed: 0.000000954
  rate: 1048576000000.000000000
  ...
ok 2 benchmark finished
# c::asec
should not return NaN
should not return NaN
  ---
  iterations: 1000000
  elapsed: 0.000000000
  rate: inf
  ...
ok 3 benchmark finished
#
1..3
# total 3
# pass  3
#
# ok
Running benchmark: /Users/dorrinsotoudeh/Downloads/stdlib/lib/node_modules/@stdlib/math/base/special/asec/benchmark/c/cephes/benchmark.c
Resolving package path...
Package path: /Users/dorrinsotoudeh/Downloads/stdlib/lib/node_modules/@stdlib/math/base/special/asec
Resolving package manifest...
Unable to resolve package manifest.
Compiling benchmark...
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/acosh.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/airy.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/asin.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/asinh.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/atan.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/atanh.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/bdtr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/beta.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/btdtr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/cbrt.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/chbevl.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/chdtr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/const.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/cosh.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/dawsn.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/drand.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/ei.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/ellie.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/ellik.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/ellpe.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/ellpj.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/ellpk.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/exp.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/exp10.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/exp2.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/expn.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/expx2.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/fabs.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/fac.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/fdtr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/floor.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/fresnl.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/gamma.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/gdtr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/hyp2f1.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/hyperg.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/i0.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/i1.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/igam.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/igami.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/incbet.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/incbi.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/isnan.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/iv.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/j0.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/j1.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/jn.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/jv.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/k0.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/k1.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/kn.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/kolmogorov.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/log.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/log10.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/log2.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/lrand.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/lsqrt.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/mtherr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/nbdtr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/ndtr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/ndtri.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/pdtr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/polevl.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/polylog.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/pow.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/powi.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/psi.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/rgamma.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/round.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/setprec.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/shichi.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/sici.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/sin.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/sincos.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/sindg.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/sinh.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/spence.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/sqrt.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/stdtr.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/struve.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/tan.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/tandg.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/tanh.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/unity.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/yn.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/zeta.c'
clang: error: no such file or directory: '/Users/dorrinsotoudeh/Downloads/stdlib/deps/build/moshier_cephes/cephes/double/zetac.c'
make[1]: *** [benchmark.out] Error 1
Error when attempting to compile benchmark.
ERROR: An error was encountered during execution.
make: *** [benchmark-c-files] Error 1
Encountered an error when running C benchmarks.
error: failed to push some refs to 'https://github.com/dorrin-sot/stdlib.git'
```

**Comment by kgryte** [comment]
The Git hooks are failing. This means that you currently have bugs in the code you are trying to push. Namely, in this case, the value ranges in the benchmarks are not valid for particular function in question. This likely stems from simply copy-and-pasting code from a different package and not modifying the files accordingly.

**Comment by dorrin-sot** [comment]
@kgryte Ohhh right sorry I didn't really look at the benchmarks (I don't know `C`, or `R`, etc. :( )

**Comment by kgryte** [comment]
Also, I don't believe Cephes has a `csch` function. And if not, those benchmarks should be removed. We typically only benchmark other languages (C, R, Python, Julia, etc) when those environments have a corresponding API. If they don't, we don't include the benchmarks.

**Comment by dorrin-sot** [comment]
Oh ok I saw that other packages were using the alternative formula in those cases and thought I should use the same; for example I used `1 / sinh(x)` for `csch(x)`'s benchmark in `C`

**Comment by kgryte** [comment]
That is fine. But for libraries like Cephes or Boost, unless there is a direct counterpart, no need to include.

**Review by kgryte — APPROVED** [review]
This PR needs some refactoring and clean-up; however, I'll do this on our end. Thanks for the contribution, @dorrin-sot.

**Comment by kgryte** [comment]
Refactored and cleaned-up in https://github.com/stdlib-js/stdlib/commit/0a90a2435502c0060106ce4a4cd2a3be494b050b.

**Pull request merged**
