### PR TITLE
test: achieve 100% test coverage for `blas/ext/base/dnansumkbn2`

### LINKED ISSUE #3074: [RFC]: Incomplete code coverage for `blas/ext/base/dnansumkbn2`
see https://coverage.stdlib.io/blas/ext/base/dnansumkbn2/index.html.

Need to add a test case in each of the relevant test files. The test case should handle the situation where the stride is `0` and the first element is `NaN`.

For reference see #3051

### PR DESCRIPTION
**Pull request by Neerajpathak07**
Resolves #3074 

## Description

This pull request:

-  Adds test cases to achieve 100% test coverage for the file:- `blas/ext/base/dnansumkbn2`

## Related Issues

This pull request:

-   resolves #3074 

## Questions

No.

## Other

No.

## Checklist

-   [x] Read, understood, and followed the [contributing guidelines](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md)

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Review by Planeshifter — CHANGES_REQUESTED** [review]
Thanks for opening a PR!

Please have a look at the failing CI checks. 
Notice also that the `.ndarray` method has a different function signature than the main `dnansumkbn2` one, expecting four arguments.

**Comment by Neerajpathak07** [comment]
@Planeshifter sure I'll look into the falling checks and implement the necessary changes.

**Comment by Neerajpathak07** [comment]
@Planeshifter I'm finding it difficult to set up an environment and run those test cases could you help me a bit?

**Comment by headlessNode** [comment]
@Neerajpathak07 Follow this guide https://github.com/stdlib-js/stdlib/blob/develop/docs/development.md

**Pull request closed without merging**
