### PR TITLE
feat: add native C implementation for acsc

### LINKED ISSUE #859: [RFC]: Add C implementation for `@stdlib/math/base/special/acsc`
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/acsc`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/acsc/).

```c
double stdlib_base_acsc( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by rajutkarsh07**
Resolves  #859

## Description

> What is the purpose of this pull request?

This pull request:
- Add native C implementation for acsc.

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves stdlib-js/stdlib/issues/859

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by rajutkarsh07** [comment]
@Planeshifter @kgryte @Pranavchiku please review this

**Comment by Pranavchiku** [comment]
I’ll review it in a while

**Review by Pranavchiku — CHANGES_REQUESTED** [review]
There are a lot of files missing, please refer #1429 and proceed.

**Comment by kgryte** [comment]
@Pranavchiku You already opened a PR for this: https://github.com/stdlib-js/stdlib/pull/1298

**Comment by kgryte** [comment]
@Pranavchiku I think this PR should be closed in favor of your previous PR which only needs a few small changes to get over the finish line.

**Comment by rajutkarsh07** [comment]
@kgryte I will complete PR submitted by @Pranavchiku  with the required changes

**Comment by kgryte** [comment]
@rajutkarsh07 You'd need commit access to his PR and make the changes, which I don't think you have. I think it is probably better if @Pranavchiku finishes that PR and you work on a separate issue.

**Comment by kgryte** [comment]
I'm going to close this in favor of #1298.

**Pull request closed without merging**
