### PR TITLE
feat: add `blas/base/caxpy`

### PR DESCRIPTION
**Pull request by aman-095**
## Description

> What is the purpose of this pull request?

This RFC proposes to add a routine to scale values of input complex double-precision floating-point vector by another complex double-precision floating-point constant and add the result to another complex double-precision floating-point vector as defined in [BLAS Level 1](http://www.netlib.org/blas/#_level_1) routines. Specifically adding `@stdlib/blas/base/caxpy` is proposed.

## Related Issues

> Does this pull request have any related issues?

None.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by aman-095** [comment]
Hey, @kgryte While implementing the C / Fortran implementation for the `caxpy` routine, I realized that it also requires `scabs1` routine. So, I am working on `dcabs1` and `scabs1` now to remove the blocker for `caxpy` and `igamax`.

**Comment by kgryte** [comment]
@aman-095 Sounds good!

**Comment by kgryte** [comment]
@aman-095 Are you planning on adding the C/Fortran implementation to this PR or in a follow-up PR?

**Comment by kgryte** [comment]
@aman-095 Looks like in your refactoring commit, you removed the C/Fortran implementation. Was this intentional?

**Comment by aman-095** [comment]
Hey, @kgryte, I have applied changes here based on #2468.

**Review by kgryte — APPROVED** [review]
LGTM. Thanks, @aman-095!

**Pull request merged**
