### PR TITLE
Add debounce function

### PR DESCRIPTION
**Pull request by aminya**
## Feel free to edit this branch

Resolves # .

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [ ] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
-   [ ] Read and understand the [Code of Conduct][code-of-conduct].
-   [ ] Read and understood the [licensing terms][license].
-   [ ] Searched for existing issues and pull requests **before** submitting this pull request.
-   [ ] Filed an issue (or an issue already existed) **prior to** submitting this pull request.
-   [ ] Rebased onto latest `develop`.
-   [ ] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[license]: https://github.com/stdlib-js/stdlib/blob/develop/LICENSE

### CODE REVIEW

**Comment by aminya** [comment]
TODO: keep up with all the contributing requirements.

**Comment by kgryte** [comment]
@aminya Thanks for working on this! This has been on our todo list for some time, so this is certainly a welcome addition. Let us know if you have any questions or encounter any issues. :)

**Comment by aminya** [comment]
Unfortunately, I had to remove this repo from my hard drive to free up space as it was taking more than 2 GB of space. Feel free to edit and push to this branch.

**Comment by kgryte** [comment]
Just going to close this out.

**Pull request closed without merging**
