### PR TITLE
Replace internal constants with package constants

### LINKED ISSUE #74: Update base math implementations to use package constants
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue.

Some of the base implementations in the `stdlib` math use constants internally which are available as packages; e.g., `@stdlib/math/constants/float64-half-pi`, etc.

To ensure consistency across the codebase, would be of benefit to replace internal constants with package constants, where available.

For constants not having package constants, these values can stay as is.

## Related Issues

> Does this issue have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/master/FAQ.md

### PR DESCRIPTION
**Pull request by chrisdamba**
Resolves #74.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

* [x] Read, understood, and followed the [contributing guidelines][contributing], including the relevant style guides.
* [x] Read and understand the [Code of Conduct][code-of-conduct].
* [x] Read and understood the [licensing terms][license].
* [x] Searched for existing issues and pull requests __before__ submitting this pull request.
* [x] Filed an issue (or an issue already existed) __prior to__ submitting this pull request.
* [x] Rebased onto latest `develop`.
* [x] Submitted against `develop` branch.

## Description

> What is the purpose of this pull request?

This pull request:

* Replaces the pi/2 and pi/4 internal constants with package constants.

## Related Issues

> Does this pull request have any related issues?

This pull request:

* resolves #74

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

---

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/master/CONTRIBUTING.md
[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[license]: https://github.com/stdlib-js/stdlib/blob/master/LICENSE

### CODE REVIEW

**Comment by kgryte** [comment]
Thanks! Depending on the outcome of #76, we would need to update this PR.

**Comment by kgryte** [comment]
Created issue #76, which proposes a new constant.

**Comment by Planeshifter** [comment]
Think we should rule out `@stdlib/math/constants/float64-quarter-pi`. I would be fine with `@stdlib/math/constants/float64-fourth-pi`; if we believe we might have many constants with denominators >4, might be better to go with `pi-over-four`, although I am not sure whether that's the case.

**Comment by kgryte** [comment]
@Planeshifter Can we shift the discussion to the relevant RFC issue?

**Comment by Planeshifter** [comment]
Moved the comment there.

**Comment by kgryte** [comment]
Thanks!

**Comment by kgryte** [comment]
@chrisdamba Would you be up for submitting the `fourth-pi` constant as a separate PR? This way we have a clean issue/PR correspondence. This PR can simply be updating packages to use said constant.

**Comment by chrisdamba** [comment]
Sure, sorry for the misunderstanding

**Comment by kgryte** [comment]
No worries! :)

**Comment by kgryte** [comment]
@chrisdamba Now that `fourth-pi` has landed, you should be able to clean this PR by doing a `git reset --hard <commit>` and making the intended changes.

**Comment by chrisdamba** [comment]
Cleaning up this PR

**Pull request closed without merging**
