### PR TITLE
feat: add `napi/create-float`

### PR DESCRIPTION
**Pull request by aman-095**
## Description

> What is the purpose of this pull request?

This RFC proposes add C APIs for converting a single-precision floating-point C value to a JavaScript object.

This is the reverse of [`@stdlib/napi/argv-float`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/napi/argv-float).

Package: `@stdlib/napi/create-float`

## Related Issues

> Does this pull request have any related issues?

None. 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by aman-095** [comment]
Required for the implementation of `scabs1`, and subsequently for `cscal`, and `caxpy`.

**Comment by kgryte** [comment]
@aman-095 There is no "float" type in the Node.js native add-on API. You can use `napi/create-double` and something along the lines of

```
STDLIB_NAPI_CREATE_DOUBLE( env, (double)foo(), v );
```

This is already done, e.g., in [`sasum`](https://github.com/stdlib-js/stdlib/blob/c65c95104ca154b32d03b6282fd4b2325b049e1f/lib/node_modules/%40stdlib/blas/base/sasum/src/addon.c#L40).

**Comment by kgryte** [comment]
Also, why is this necessary for `scabs1`? You're already using `STDLIB_MATH_BASE_NAPI_MODULE_C_F`, which, I believe, should be fine for this purpose.

**Comment by aman-095** [comment]
Hey, @kgryte I thought to keep the files with the same structure as the other blas routines, and hence not use the `STDLIB_MATH_BASE_NAPI_MODULE_C_F`.

**Comment by aman-095** [comment]
Also, I noticed that there is no "float" type in the Node.js native add-on API, but I thought to add it in `stdlib`. But with the approach you mentioned, I think we don't require that. And yes, I was unsure whether we could use `STDLIB_MATH_BASE_NAPI_MODULE_C_F`. But now that I went through `sasum`, I have updated the `scabs1` as well. Thanks for the information.

**Comment by kgryte** [comment]
@aman-095 Can we go ahead and close this PR? Given that there is no concept of a single-precision scalar in JavaScript, I don't believe it makes sense to add this package, and your recent changes to `scabs1` seem reasonable to me.

**Comment by aman-095** [comment]
Yes, @kgryte we can close this PR.

**Pull request closed without merging**
