### PR TITLE
#1613 Update README.md benoulli

### LINKED ISSUE #1613: [RFC]: improve README examples of `stats/base/dists/bernoulli` namespace
### Description

This RFC proposes to improve the [README examples](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base/dists/bernoulli#examples) of the `stats/base/dists/bernoulli` namespace package. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality.

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the [contents](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base/dists/bernoulli) of the `stats/base/dists/bernoulli` namespace and identify interesting functions and packages to showcase.
- Update the example code block in the "Examples" section of the README for the `stats/base/dists/bernoulli` namespace and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by kunal-511**
improve README examples of stats/base/dists/bernoulli namespace

Resolves # .

## Description

> What is the purpose of this pull request?

This pull request: To add examples to the lib/node_modules/@stdlib/stats/base/dists/bernoulli  namespace

-   a
-   b
-   c

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1613
-   fixes #

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kunal-511** [comment]
@stdlib-bot Please review my PR? 
Also tell is this the right way

**Comment by kunal-511** [comment]
@Planeshifter  Please review my PR. Some checks failed can you explain to me why? I am new here and I want to contribute

**Review by Planeshifter — CHANGES_REQUESTED** [review]
@kunal-511 As-is, this contribution cannot be accepted. Notice that we use ES5 syntax (e.g., `var` instead of `let` and `const`) in the example code. Also, don't generate example code with the help of an LLM such as ChatGPT given that they are prone to hallucinate. `const { randomNumber } = require('@stdlib/random');` does not exist, for example.

**Comment by kunal-511** [comment]
@Planeshifter 
So sorry for this I will not repeat it next time.

**Pull request closed without merging**
