### PR TITLE
feat: Added C implementation for `@stdlib/math/base/special/fibonacci-index`

### LINKED ISSUE #1756: [RFC]: Add C implementation for `@stdlib/math/base/special/fibonacci-index`
### Description

This RFC proposes adding native C implementation for `@stdlib/math/base/special/fibonacci-index`.
```
double stdlib_base_fibonacci_index( const double F );
```

### Related Issues

Tracked in issue #649.

### Questions

I am not sure about the method's signature. In the original JavaScript code, both the return type and the parameter are {NonNegativeInteger}. However, in some tests they take on the value NaN, which as far as I know does not exist for integer types in C. For this reason, I decided on using double, but please tell me if there is a more suitable solution.

### Other

The implementation depends on the `round` function, which is addressed in #735. I can use the round method from C until the method is implemented in stdlib, and I can also contribute to implementing `round`.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by vivek-anand-singh**
Resolves #1756

## Description

> What is the purpose of this pull request?

This pull request:

 This adds the native C implementation for `@stdlib/math/base/special/fibonacci-index.`

<pre>double stdlib_base_fibonacci_index( const double F ); </pre>

## Related Issues

> Does this pull request have any related issues?
No

This pull request:

-   resolves #1756
-   fixes #1756

## Questions

> Any questions for reviewers of this pull request?
I am not sure about the benchmark folder . Can you please guide over it.
I tried understanding the format from abs which was implemented inside `@stdlib/math/base/special/abs` .

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
@vivek-anand-singh This PR cannot be accepted as is.

1. This PR also includes `cusome-by`. Please keep your PRs to only 1 feature. Multiple features should be split across separate PRs.
2. You added `@stdlib/math/special/fibonacci-index`, and not `@stdlib/math/base/special/fibonacci-index`. Adding the former is not what was requested.

**Review by kgryte — CHANGES_REQUESTED** [review]
Please follow conventions elsewhere in the project. For submitting PRs, please see recent merged PRs for an idea of what is expected. Given that the intent was to add `@stdlib/math/base/special/fibonacci-index`, I suggest examining the PRs linked to #649.

**Comment by kgryte** [comment]
As #1756 has already been implemented in #2272, I will go ahead and close this PR. @vivek-anand-singh I suggest finding another issue to work on, perhaps asking on #649 where work is being tracked.

**Comment by vivek-anand-singh** [comment]
@kgryte, I deeply apologize for the mistakes in my PR.

For the first issue, I previously raised a PR on the cusome-by branch (PR #2661). When the second issue got assigned to me, I mistakenly assumed I was on the main branch and didn't switch branches. This oversight affected the PR, and I take full responsibility for it.

For the second issue, I overlooked the base folder, which I fully accept was my fault. I should have been more thorough in reviewing the project structure.

I sincerely apologize for any inconvenience caused. I genuinely want to learn from this experience and contribute positively to the organization in the future. I'm truly sorry for the oversight and would be grateful for another opportunity to make things right.

**Pull request closed without merging**
