### PR TITLE
refactor: update `blas/ext/base/ssortins` to follow current project conventions

### LINKED ISSUE #1538: [RFC]: refactor `blas/ext/base/ssortins` to follow current project conventions
### Description

This RFC proposes refactoring [`@stdlib/blas/ext/base/ssortins`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/blas/ext/base/ssortins) to follow current project conventions.

These conventions are outlined in more detail in https://github.com/stdlib-js/stdlib/issues/788. Namely, we want to migrate from C++ add-on interfaces to C add-on interfaces and then make various style and simplification changes.

Some example commits which perform most, if not all, of the requested changes include https://github.com/stdlib-js/stdlib/commit/d66d80cfcbab1da95cb5ae8cfae4a1fc4c5129d1 (saxpy),  https://github.com/stdlib-js/stdlib/commit/3c82fe7b6c0f9fd6ef02c86d6e2024d708ac8c14 (cswap), and https://github.com/stdlib-js/stdlib/commit/5b15c9675be434c0e11b1ec1e1f78d7b089abbcd (dasum).

### Related Issues

Related issues #788, #1152.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

### PR DESCRIPTION
**Pull request by aayush0325**
Resolves #1538 .

## Description

> What is the purpose of this pull request?

This pull request:

-   Refactors `blas/ext/base/ssortins` to follow current project conventions.
-   Added addons in C instead of C++
-   Updated examples and style as per the given commits in the issue #1538 .
-  https://github.com/stdlib-js/stdlib/commit/d66d80cfcbab1da95cb5ae8cfae4a1fc4c5129d1 (saxpy), https://github.com/stdlib-js/stdlib/commit/3c82fe7b6c0f9fd6ef02c86d6e2024d708ac8c14 (cswap), and https://github.com/stdlib-js/stdlib/commit/5b15c9675be434c0e11b1ec1e1f78d7b089abbcd (dasum).
## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves #1538 

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

-  Open to reviews and willing to work on this if something else was expected from this PR!

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by aayush0325** [comment]
@Planeshifter ready for initial review!

**Comment by aayush0325** [comment]
this branch has a lot of garbage commits which i made while trying to figure things out, i can raise a new, clean PR from another branch if needed.

**Comment by Planeshifter** [comment]
@aayush0325 No reason to worry about the commits, we are squashing the commits anyway when merging PRs to ensure a clean git history. I just did a review and made a few changes, but overall your PR looked great! Thanks for your contribution!

**Comment by aayush0325** [comment]
Thank you for you help and support!

**Pull request merged**
