### PR TITLE
docs: use correct operator for modulus in `math/base/special/fmod`

### PR DESCRIPTION
**Pull request by gunjjoshi**
## Description

> What is the purpose of this pull request?

This pull request:

-   uses correct operator for modulus in examples in [`math/base/special/fmod`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/fmod/examples/index.js#L32).

## Related Issues

> Does this pull request have any related issues?

None.

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by Planeshifter** [comment]
@gunjjoshi Would you mind updating the `README.md` file as well, please?

**Comment by gunjjoshi** [comment]
> @gunjjoshi Would you mind updating the `README.md` file as well, please?

Sure, done!

**Review by kgryte — APPROVED** [review]
LGTM.

**Comment by kgryte** [comment]
The lint failure is due to `cppcheck` and can be ignored for the purposes of this PR.

**Pull request merged**
