### PR TITLE
feat: add `iter/cuany`

### PR DESCRIPTION
**Pull request by RidamGarg**
## Description

> What is the purpose of this pull request?

This pull request:
adds the implementation of @stdlib/iter/cuany

## Related Issues

> Does this pull request have any related issues?

This pull request:

-   resolves [RFC]: add @stdlib/iter/cuany #2331

## Questions

> Any questions for reviewers of this pull request?

No.

## Other

> Any other information relevant to this pull request? This may include screenshots, references, and/or implementation notes.

No.

## Checklist

> Please ensure the following tasks are completed before submitting this pull request.

-   [x] Read, understood, and followed the [contributing guidelines][contributing].

* * *

@stdlib-js/reviewers

[contributing]: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md

### CODE REVIEW

**Comment by kgryte** [comment]
@RidamGarg Would you mind updating your OP to use our PR template? You should have been prompted to use that template when opening the PR. That template includes a checkbox that you need to check in order to allow your contributions to be included in the project.

Also, it looks like CI is failing for your PR, so you'll want to address the lint and other errors before we perform a review. Thanks!

**Comment by kgryte** [comment]
Also, you're attempting to open a PR from your `main` branch. I suggest that moving forward you use a more descriptive name. For further info, see our contributing [guide](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md#step-3-branch), which then links to our branching guide.

**Comment by RidamGarg** [comment]
Hello @kgryte , Thanks for pointing out the problems. Can I get The PR template as I am not able to find it now. For linting errors, I am able to solve them for all the other files. But not able to solve it for Readme.md file & repl.txt. Can you help me with that?

**Comment by kgryte** [comment]
PR template can be found here: https://github.com/stdlib-js/stdlib/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

**Comment by kgryte** [comment]
For an example, see other PRs. E.g., https://github.com/stdlib-js/stdlib/pull/2443.

**Comment by RidamGarg** [comment]
Done @kgryte

**Comment by kgryte** [comment]
@RidamGarg It looks like you did not follow the suggestions left in https://github.com/stdlib-js/stdlib/pull/2358#pullrequestreview-2111801678. For all future PRs, you need to follow our branching guidance. Any future PRs which don't won't be reviewed or accepted, as failure to follow that guidance results in significantly more work for reviewers.

For this PR, I had to refactor the entirety of the implementation. Your prior approach simply consumed the entire source iterator, created a temporary array, and then returned a new iterator. You should ask, however, what happens if the source iterator has an infinite number of values?

Additionally, you'll want to adhere more closely to our conventions: style, language (e.g., descriptions), and prior art. We place a high value on consistency.

I've tested things locally, so I'll go ahead and merge. But any future PRs in which CI does not pass due to branching issues or lint errors will not be accepted.

**Review by kgryte — APPROVED** [review]

**Comment by RidamGarg** [comment]
Okay @kgryte, I'll keep this in mind in the future. Sorry for the inconvenience caused.

**Pull request merged**
